name: user_repository
description: "A repo that handles user"
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #cupertino_icons: ^1.0.6
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
